@DocumentArchive.APIs_HostAddress = https://localhost:44317


GET {{DocumentArchive.APIs_HostAddress}}/categories/
Accept: application/json

###


GET {{DocumentArchive.APIs_HostAddress}}/categories/d8de7421-f37c-40db-a93c-0fded871b002
Accept: application/json

###


POST   {{DocumentArchive.APIs_HostAddress}}/categories/
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
  "title": "sample12"
}

###


PUT   {{DocumentArchive.APIs_HostAddress}}/categories/
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
  "categoryId":"d8de7421-f37c-40db-a93c-0fded871b002",
  "title": "sample23332",
  "isApprovalNeeded": true
}

###






